### ISSUE TITLE
第十步-- 找到第一个 8i0找不到阿 求大老解答

### ISSUE THREAD

**Issue by aboymobi** [geuomao/WAEQySRL64fXpNGL#1]
第十步
  找到第一个 8i0
  把 0 改成 ' + str(count * 20) + '
第十步-- 找到第一个 8i0找不到阿 求大老解答
-------------------------------------------------------------------------------------------
运行后报错
-----------------------------------------------------------------------------------------
>python sym.py
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\stem\socket.py", line 535, in _make_socket
    control_socket.connect((self.address, self.port))
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sym.py", line 123, in <module>
    controller = Controller.from_port(port=9151)
  File "C:\ProgramData\Anaconda3\lib\site-packages\stem\control.py", line 1033, in from_port
    control_port = stem.socket.ControlPort(address, port)
  File "C:\ProgramData\Anaconda3\lib\site-packages\stem\socket.py", line 503, in __init__
    self.connect()
  File "C:\ProgramData\Anaconda3\lib\site-packages\stem\socket.py", line 172, in connect
    self._socket = self._make_socket()
  File "C:\ProgramData\Anaconda3\lib\site-packages\stem\socket.py", line 538, in _make_socket
    raise stem.SocketError(exc)
stem.SocketError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

**Comment by mengxiangke** [comment]
> ## 第十步
> 找到第一个 8i0
> 把 0 改成 ' + str(count * 20) + '
> 第十步-- 找到第一个 8i0找不到阿 求大老解答
> ## 运行后报错
> > python sym.py
> > Traceback (most recent call last):
> > File "C:\ProgramData\Anaconda3\lib\site-packages\stem\socket.py", line 535, in _make_socket
> > control_socket.connect((self.address, self.port))
> > ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "sym.py", line 123, in
> controller = Controller.from_port(port=9151)
> File "C:\ProgramData\Anaconda3\lib\site-packages\stem\control.py", line 1033, in from_port
> control_port = stem.socket.ControlPort(address, port)
> File "C:\ProgramData\Anaconda3\lib\site-packages\stem\socket.py", line 503, in **init**
> self.connect()
> File "C:\ProgramData\Anaconda3\lib\site-packages\stem\socket.py", line 172, in connect
> self._socket = self._make_socket()
> File "C:\ProgramData\Anaconda3\lib\site-packages\stem\socket.py", line 538, in _make_socket
> raise stem.SocketError(exc)
> stem.SocketError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

大佬解决了没

**Comment by geuomao** [comment]
等我有时间更新一下
